services:
  # A Docker web service
  - type: web
    name: TeraboxDLBot
    env: python
    startCommand: python3 -m bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/HKCS04/TeraDLBot/tree/main # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
